### PR TITLE
Updated filament from 1.9.25 -> 1.10.6

### PR DESCRIPTION
**Pull request by RGregat**
* Recompiled all *.mat files
* Fixed issues because of removed filament APIs.

### CODE REVIEW

**Review by ThomasGorisse — CHANGES_REQUESTED** [review]
Can you also include the ones in ux/assets-sources/materials ?
You can move them directly to core/assets-sources/materials in order to not forget them every time.

Did you made tests to be sure everything is OK?
An Assert error should crash the app if it's not the case.

Can you also have a look at this bug https://github.com/ThomasGorisse/sceneform-android-sdk/pull/70 to see if it has been resolved with the latest Filament version?

**Comment by RGregat** [comment]
* I updated the `*.mat` files from the **core** and **ux** module.
* I tested the filament update on all samples and my personal project.

> Can you also have a look at this bug #70 to see if it has been resolved with the latest Filament version?

* Do you mean the necessity to add the following in `onViewCreated`?

```java
if (renderer != null) {
    renderer.getFilamentView().setColorGrading(
        new ColorGrading.Builder()
            .toneMapping(ColorGrading.ToneMapping.FILMIC)
            .build(EngineInstance.getEngine().getFilamentEngine())
    );
}
```

**Comment by ThomasGorisse** [comment]
> Do you mean the necessity to add the following in onViewCreated?
> if (renderer != null) {
>     renderer.getFilamentView().setColorGrading(
>         new ColorGrading.Builder()
>             .toneMapping(ColorGrading.ToneMapping.FILMIC)
>             .build(EngineInstance.getEngine().getFilamentEngine())
>     );
> }

Exactly!

BTW, nothing related but searching for a way to draw polygons I found your great issue (and own answer) here https://github.com/google-ar/sceneform-android-sdk/issues/443
Thanks a lot, it greatly helped me.
If you are still working on it, I strongly recommend you moving to [JTS Topology Suite](https://github.com/locationtech/jts) instead of Poly2Tri for Delaunay triangulation.
It works much better, it's simpler and doesn't forbid intersection vertices.

**Comment by RGregat** [comment]
> Exactly!

* I have no idea how to spot the difference within the sample projects, but for my personal project I have still the same coloring issue, when I'm not setting the ColorGrading to FILMIC in onViewCreated.  

> BTW, nothing related but searching for a way to draw polygons I found your great issue (and own answer) here google-ar#443
Thanks a lot, it greatly helped me.
If you are still working on it, I strongly recommend you moving to JTS Topology Suite instead of Poly2Tri for Delaunay triangulation.
It works much better, it's simpler and doesn't forbid intersection vertices.

Not a bad idea, but I abandoned the mentioned idea. I have a Polygon drawing node which still uses poly2tri. Maybe I change this in the near future! Thanks

**Comment by RGregat** [comment]
> Can you also include the ones in ux/assets-sources/materials ?
You can move them directly to core/assets-sources/materials in order to not forget them every time.

* Does it make sense to move them to the **core** module? I mean the VideoNode expects the compiled `*.filamat` files in the **ux** module. So I change the oh I forgot to compile the `*.mat` files from the **ux** module, to oh I forgot to copy the `*.filamat` files to the **ux** module :D

**Comment by ThomasGorisse** [comment]
> I have no idea how to spot the difference within the sample projects, but for my personal project I have still the same coloring issue, when I'm not setting the ColorGrading to FILMIC in onViewCreated.

I asked Filament here: https://github.com/google/filament/issues/3909

> Does it make sense to move them to the core module? I mean the VideoNode expects the compiled *.filamat files in the ux module. So I change the oh I forgot to compile the *.mat files from the ux module, to oh I forgot to copy the *.filamat files to the ux module :D

Do it as you feel. I'm also not against moving `VideoNode` to core.

**Comment by ThomasGorisse** [comment]
Even more because I really ask myself if it's still make sense to have core, ux, sceneform instead of a unique sceneform module.

**Comment by RGregat** [comment]
> Even more because I really ask myself if it still make sense to have core, ux, sceneform instead of a unique sceneform module.

true
In general, the package-structure could need an overhaul. Especially the rendering packag is to big, some sub packages would be beneficial.
We should do that in another branch

**Comment by ThomasGorisse** [comment]
> In general, the package-structure could need an overhaul. Especially the rendering packag is to big, some sub packages would be beneficial.

An enormous clean would be enormously benefit.
The question is more to know who and when.
Even more because I contacted most of the Sceneform articles writers this week to tell them that we are here and great.
Some answered that they will update their old article sfb code and 1.1.15/1.1.16 dependencies parts.
So It's time to have a clean/fixed version or to keep it mostly safe like it is.

> We should do that in another branch

I'm pretty much against having separated branch except for the PRs because it's a nightmare to maintain. 

BTW2, some DeptPoint, InstantPlacement, Reticle spoil:

https://user-images.githubusercontent.com/6597529/125099728-9e666300-e0d8-11eb-99cb-559641745eb4.mp4

It's working awesomely. I just need to clean it before pushing.

**Comment by ThomasGorisse** [comment]
!It's working awesomely. I just need to clean it before pushing.
It's funny cause I'm actually plastering my wall (In real life ;-)) and I can see the difference while doing it with depth points and the reticle.

**Comment by RGregat** [comment]
> I'm pretty much against having separated branch except for the PRs because it's a nightmare to maintain.

Same here, i meant not this current PR :)

**Comment by RGregat** [comment]
> An enormous clean would be enormously benefit.
The question is more to know who and when.
Even more because I contacted most of the Sceneform articles writers this week to tell them that we are here and great.
Some answered that they will update their old article sfb code and 1.1.15/1.1.16 dependencies parts.
So It's time to have a clean/fixed version or to keep it mostly safe like it is.

* II would volunteer to do the cleanup, or at least to try it. But with your announcement to the writers, I think it make sense to wait with such a huge change.

**Comment by ThomasGorisse** [comment]
I hope they can now include some evolving code block like a gist displaying  our master  GitHub samples code.

**Pull request merged**
