### PR TITLE
Added VideoNode and updated video-texture sample.

### PR DESCRIPTION
**Pull request by Venthorus**
Contains the new VideoNode for showing a video from a MediaPlayer instance inside a node in Sceneform.
The materials are now precompiled, however the original material files were also added to the project.
The video-texture sample has also been updated to make use of VideoNode.

### CODE REVIEW

**Comment by ThomasGorisse** [comment]
Wow!!!! You made an awesome job.
Everything in your code looks great and clean.
I'll check your code more precisely as soon as possible.

Thanks a lot from everyone here!!!!

**Comment by Venthorus** [comment]
There is a minor issue where a chroma key video initially shows a black rectangle before the first frame is rendered (as is the case in your current video-texture sample) which doesn't look good. I tried some things but in the end couldn't avoid it completely, so I left that out for this pull request. Might get back to it later at some point.

**Comment by ThomasGorisse** [comment]
Everything is simply perfect and clean.
I just added some docs.

Thanks a lot from everyone here.

**Comment by Venthorus** [comment]
No problem. I guess I was the right person for this task as I did something like this before and you had the right intuition to ask me.

If you want you can actually update the chroma key example video in the README because now only the lion throws a shadow instead of the actual model. I still had the chroma key material from the original Sceneform where the blending was "masked" instead of "transparent", which makes it look realistic.

**Pull request merged**
