### PR TITLE
Set FILMIC tone-mapping in AR examples

### PR DESCRIPTION
**Pull request by grassydragon**

### CODE REVIEW

**Review by ThomasGorisse — CHANGES_REQUESTED** [review]
Couldn't you put `setColorGrading` inside the `onViewCreated(ArFragment arFragment, ArSceneView arSceneView)` form the `OnViewCreatedListener` ?
This listener was added to avoid the Null Pointer access to `fragment.arsceneview`.
The `onSessionInitialization(Session session)` is called nearly from the `renderer.filamentView` creation but is more dedicated to the ARCore init and might be deprecated after the more accurate recently added `OnSessionConfigurationListener`.

Is there any issue setting the color grading later in a sample workaround context ?

**Comment by grassydragon** [comment]
I have a question about CI. Will it be paid to set it up as described in another pull request?

**Comment by ThomasGorisse** [comment]
CI = Continuous Integration?
What do you mean by "will it be paid"?

**Comment by ThomasGorisse** [comment]
If this is what you mean, it could be used to generate the artifact (.aar, .pom,...) and make it available on a Snapshot/master branch version as GitHub packages but users will need to configure their GitHub Token for using it from Gradle.
And jitpack.io is doing the same without authentication.

It could also be usefull to add a compile check before pushing but I personally prefer to minimize the push process.

And it could finally maybe be used in a more complex way inside a multi repos centralized action (from what I understand).

**Comment by grassydragon** [comment]
> What do you mean by "will it be paid"
I mean whether GitHub will take money for building the project in the cloud.

> It could also be useful to add a compile check before pushing but I personally prefer to minimize the push process.
Yes, this is the main reason but, if build new releases often, this is not a big problem.

**Review by ThomasGorisse — APPROVED** [review]

**Comment by ThomasGorisse** [comment]
Thanks a lot @grassydragon

**Pull request merged**
