### PR TITLE
Fixed plane rendering

### PR DESCRIPTION
**Pull request by grassydragon**
Now planes are correctly highlighted when you look at them not from the initial point.

### CODE REVIEW

**Comment by ThomasGorisse** [comment]
Thanks a lot !!!!!
I have to admit that I'm very bad on material development and here you save the life of a lot developers from this community.
I you see overs wrong things in the materials or java code, I gave you the contributor role.

**Review by ThomasGorisse — COMMENTED** [review]
Accepted

**Comment by grassydragon** [comment]
Thank you for accepting my pull request!
Initially I planed to use Filament for my ARCore project since there was no version of Sceneform updated to the latest libraries. However, after creating a simple application I understood that I would have to implement many things from scratch that were available in Sceneform. Also, working with the Sceneform source code appeared to be less scary than I thought!
Thank you for maintaining Sceneform! If I find any problems or add new things, I will definitely contribute to this repository.

**Comment by ThomasGorisse** [comment]
You well understood the main AR problem on Android.
ARCore with Filament direct integration is not so simple at all. Some people (even in Filament team) view it as a simple Filament sample to copy/paste from the Filament repo.
This could be the case if considering that sceneform is only a bridge between ARCore Camera transformation applied to a Filament camera.

BUT here will come some questions:

"How can I place my model not only at the camera center?"
"Where are the shadows ?"
"Why does the model seems lighten while the real environnement is dark ?
"How can I place some objects depending on other ?"
...
Sceneform suffer from the fact that they originally made their own 3D render engine and model loading.
And from the complexity they introduced by enabling to much features.

In most usage case developers just want to have a glb placing in the AR environment, augmented image, video texture,...

THAT'S WHY

I'm currently working on a complete new framework more like Apple RealityCore and I really need help mostly on the material part. If you are interested in helping, I can give you the repo access on PM.

**Comment by grassydragon** [comment]
I have used AR Foundation for Unity and I like how it provides access to the AR functionality. The developer is still responsible for processing hit results and placing objects. However, it is not difficult since the objects can be added to the scene the same way it is done in other Unity applications. Planes are added to the scene by AR Foundation as normal game objects so it is simple to change their appearance by providing a custom material. Finally, the ray casting in Unity can be used to interact with object and UI elements in 3D.
AR Foundation provides abstraction for native AR frameworks (camera image rendering, virtual camera control and access to the AR functionality) but it doesn't change the way you work with the game engine. I think it would be great to have something similar for Android, for example for Filament.
Thank you for asking me to collaborate on the new framework. Unfortunately, I am working on my project so I will be able to help in the summer.

**Pull request merged**
